name: Feature Request
description: Suggest a feature or improvement
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Description
      description: A short description of your requested feature.
      placeholder: |
        What feature would you like to add to the video surveillance app?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots or wireframes
      description: >
        If applicable, please provide additional documentation that helps explain or demonstrate the feature or issue.
        You can drag-and-drop images here or paste them directly into this field.
      placeholder: |
        Attach screenshots or logs here.

  - type: textarea
    attributes:
      label: Additional Information
      description: Anything else you’d like to share?
